services:
  nextcloud:
    image: kefaslungu/hng-nextcloud
    container_name: nextcloud
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - HNG-nginx-logs:/var/log/nginx
    depends_on:
      - nextcloud

  detector:
    build: .
    container_name: hng_detector
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - HNG-nginx-logs:/var/log/nginx

volumes:
  HNG-nginx-logs:
