worker_processes auto;

events {}

http {
    log_format json_log escape=json '{'
        '"source_ip":"$remote_addr",'
        '"time":"$time_iso8601",'
        '"method":"$request_method",'
        '"path":"$request_uri",'
        '"status":$status,'
        '"bytes":$body_bytes_sent'
    '}';

    access_log /var/log/nginx/hng-access.log json_log;

    server {
        listen 80;

        location / {
            proxy_pass http://nextcloud:80;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
        }
    }
}
